on:
  push:
    branch:
      - "main"
    tags:
      - "v[0-9]+.*"

jobs:
  flakehub-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag) }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: public
          rolling: false
          tag: ${{ inputs.tag }}
