name: "latest tag"
on:
  push:
    tags:
      - v**
jobs:
  latest-tag:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update 'latest' git tag
        uses: EndBug/latest-tag@latest
